### ISSUE TITLE
folder generated as the wrong argument's value

### ISSUE THREAD

**Issue by thierrygosselin** [beiko-lab/RADProc#7]
Hi Praveen,

Something I noticed while running RADProc, the folder generated was `M2_m3`, but the  command I used was: `-M 4 -m 3 -n 4 -p 8 -x 3 -S 80 -D 7` 

**Q.** what was actually used to form a putative locus ? `-M 2` or `-M 4` like I asked ? same goes for the coverage threshold to generate a stack/putative allele.

Best
Thierry

**Comment by praveennr** [comment]
Hi Thierry,

That is because RADProc takes the nucleotide distance for primary and secondary stacks (less than specified coverage depth) as single parameter M ( the network distance). So in RADProc M = 4 will be considered as M = 2 for primary and M = 4 for secondary stacks. It is just to accommodate M+2 distance for secondary stacks, when building the RADProc graph. In case of m it is same as the value you specify. 

~Praveen

**Comment by thierrygosselin** [comment]
ok good to know
